### ISSUE TITLE
Where is the "random restart of codebook"?

### ISSUE THREAD

**Issue by LeeDoYup** [openai/jukebox#231]
I read the paper, and find that random restart is used for the unused codewords.
Where are the codes correspond to the "random restart" in training VQ-VAE???

**Comment by dvruette** [comment]
It's been a while since you asked, but since I was just trying to find out the same thing, here's the relevant lines of code for reference:
https://github.com/openai/jukebox/blob/master/jukebox/vqvae/bottleneck.py#L75-L77

The threshold for a random restart seems to be 1.0 by default. The threshold check is done after calculating the updated code usage.

**Comment by LeeDoYup** [comment]
Thanks !

**Comment by Ma-Weijian** [comment]
Hi, @dvruette . I just want to have a double check. 
So it means as long as a code has been reference once, it will not be reinited, right?

**Comment by dvruette** [comment]
Yes, I believe that’s accurate (has been a while since I’ve looked at this). Keep in mind that it’s a moving average, so as long as a code is used once per batch on average it will not be reinitialized.

**Comment by Ma-Weijian** [comment]
Thanks, I got it!

**Comment by SophusDavid** [comment]
> Hi, @dvruette . I just want to have a double check. So it means as long as a code has been reference once, it will not be reinited, right?
(doge) i meet the same problem. Thank u 👍
