### ISSUE TITLE
How to properly sample from 1B on colab

### ISSUE THREAD

**Issue by LouD49** [openai/jukebox#60]
Do i only need to change the model to "1B lyrics" in that first line or do i need to also change every reference to 5b lyrics in the code?

> model = "1b_lyrics"     
hps = Hyperparams()
hps.sr = 44100
hps.n_samples = 3 if model=='5b_lyrics' else 8
hps.name = 'samples'
chunk_size = 16 if model=="5b_lyrics" else 32
max_batch_size = 3 if model=="5b_lyrics" else 16
hps.levels = 3
hps.hop_fraction = [.5,.5,.125]

> sampling_temperature = .98
lower_batch_size = 16
max_batch_size = 3 if model == "5b_lyrics" else 16
lower_level_chunk_size = 32
chunk_size = 16 if model == "5b_lyrics" else 32
sampling_kwargs = [dict(temp=.99, fp16=True, max_batch_size=lower_batch_size,
                        chunk_size=lower_level_chunk_size),
                    dict(temp=0.99, fp16=True, max_batch_size=lower_batch_size,
                         chunk_size=lower_level_chunk_size),
                    dict(temp=sampling_temperature, fp16=True, 
                         max_batch_size=max_batch_size, chunk_size=chunk_size)]

**Comment by apeguero1** [comment]
Only keep the first line with "1b_lyrics".  The other references to "5b_lyrics" are only there to compare against the model you specify in the first line. 

For example, in `hps.n_samples = 3 if model=='5b_lyrics' else 8` the number of samples to generate will be set equal to 3 if the model is equal to "5b_lyrics" but will be set equal to 8 otherwise. "1b_lyrics" falls into the otherwise case.

**Comment by diffractometer** [comment]
@LouD49 just the first...

**Comment by LouD49** [comment]
got it, thanks!
